# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import chat_pb2 as chat__pb2


class ChatStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.receive_messages = channel.unary_stream(
            "/chat.Chat/receive_messages",
            request_serializer=chat__pb2.Empty.SerializeToString,
            response_deserializer=chat__pb2.Message.FromString,
        )
        self.send_message = channel.unary_unary(
            "/chat.Chat/send_message",
            request_serializer=chat__pb2.Message.SerializeToString,
            response_deserializer=chat__pb2.Empty.FromString,
        )


class ChatServicer(object):
    """Missing associated documentation comment in .proto file."""

    def receive_messages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def send_message(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ChatServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "receive_messages": grpc.unary_stream_rpc_method_handler(
            servicer.receive_messages,
            request_deserializer=chat__pb2.Empty.FromString,
            response_serializer=chat__pb2.Message.SerializeToString,
        ),
        "send_message": grpc.unary_unary_rpc_method_handler(
            servicer.send_message,
            request_deserializer=chat__pb2.Message.FromString,
            response_serializer=chat__pb2.Empty.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "chat.Chat", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Chat(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def receive_messages(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/chat.Chat/receive_messages",
            chat__pb2.Empty.SerializeToString,
            chat__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def send_message(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chat.Chat/send_message",
            chat__pb2.Message.SerializeToString,
            chat__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
